/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cash` | `/cash`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/customers` | `/customers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `/cash/close`; params?: Router.UnknownInputParams; } | { pathname: `/cash/open`; params?: Router.UnknownInputParams; } | { pathname: `/customer/collection`; params?: Router.UnknownInputParams; } | { pathname: `/sales/cart`; params?: Router.UnknownInputParams; } | { pathname: `/sales/payment`; params?: Router.UnknownInputParams; } | { pathname: `/sales/receipt`; params?: Router.UnknownInputParams; } | { pathname: `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/customer/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/inventory/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cash` | `/cash`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/customers` | `/customers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownOutputParams; } | { pathname: `/cash/close`; params?: Router.UnknownOutputParams; } | { pathname: `/cash/open`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/collection`; params?: Router.UnknownOutputParams; } | { pathname: `/sales/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/sales/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/sales/receipt`; params?: Router.UnknownOutputParams; } | { pathname: `/scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/inventory/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cash${`?${string}` | `#${string}` | ''}` | `/cash${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/customers${`?${string}` | `#${string}` | ''}` | `/customers${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/inventory${`?${string}` | `#${string}` | ''}` | `/inventory${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sales${`?${string}` | `#${string}` | ''}` | `/sales${`?${string}` | `#${string}` | ''}` | `/cash/close${`?${string}` | `#${string}` | ''}` | `/cash/open${`?${string}` | `#${string}` | ''}` | `/customer/collection${`?${string}` | `#${string}` | ''}` | `/sales/cart${`?${string}` | `#${string}` | ''}` | `/sales/payment${`?${string}` | `#${string}` | ''}` | `/sales/receipt${`?${string}` | `#${string}` | ''}` | `/scanner${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cash` | `/cash`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/customers` | `/customers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/inventory` | `/inventory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `/cash/close`; params?: Router.UnknownInputParams; } | { pathname: `/cash/open`; params?: Router.UnknownInputParams; } | { pathname: `/customer/collection`; params?: Router.UnknownInputParams; } | { pathname: `/sales/cart`; params?: Router.UnknownInputParams; } | { pathname: `/sales/payment`; params?: Router.UnknownInputParams; } | { pathname: `/sales/receipt`; params?: Router.UnknownInputParams; } | { pathname: `/scanner`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | `/customer/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/inventory/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/customer/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/inventory/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
